//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMIN()
        {
            this.CHATs = new HashSet<CHAT>();
            this.CHITIETGIAYCNs = new HashSet<CHITIETGIAYCN>();
        }
    
        public int MAADM { get; set; }
        public string NAME { get; set; }
        public string EMAILADM { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string PHONE { get; set; }
        public string AVATAR { get; set; }
        public Nullable<System.DateTime> AGE { get; set; }
        public string SEX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAT> CHATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIAYCN> CHITIETGIAYCNs { get; set; }
        public virtual THONGTIN THONGTIN { get; set; }
    }
}
