//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETGIAYCN
    {
        public int MAGCN { get; set; }
        public Nullable<int> MAADM { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual GIAYCN GIAYCN { get; set; }
    }
}
