//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTIN
    {
        public int MATT { get; set; }
        public string TENTT { get; set; }
        public string NOIDUNGTT { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public string HINHMINHHOA { get; set; }
        public Nullable<int> MALTT { get; set; }
        public Nullable<int> MADM { get; set; }
        public string FileName { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual LOAITT LOAITT { get; set; }
    }
}
